//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pooshineh.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClothingStoreEntities1 : DbContext
    {
        public ClothingStoreEntities1()
            : base("name=ClothingStoreEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Cart> Table_Cart { get; set; }
        public virtual DbSet<Table_CartItem> Table_CartItem { get; set; }
        public virtual DbSet<Table_Categories> Table_Categories { get; set; }
        public virtual DbSet<Table_Products> Table_Products { get; set; }
        public virtual DbSet<Table_Roles> Table_Roles { get; set; }
        public virtual DbSet<Table_User> Table_User { get; set; }
        public virtual DbSet<Table_Discounts> Table_Discounts { get; set; }
        public virtual DbSet<Table_OrderDetails> Table_OrderDetails { get; set; }
        public virtual DbSet<Table_Orders> Table_Orders { get; set; }
    }
}
