//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pooshineh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Table_ProductColor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_ProductColor()
        {
            this.Table_ProductSize = new HashSet<Table_ProductSize>();
        }
    
        public int ProductColorID { get; set; }
        public int ProductID { get; set; }
        [Display(Name = "رنگ")]
        [Required(ErrorMessage = "فیلد {0} اجباری است.")]
        public string Color { get; set; }
    
        public virtual Table_Products Table_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_ProductSize> Table_ProductSize { get; set; }
    }
}
