//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pooshineh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_ProductDetails
    {
        public int ProductDetailsID { get; set; }
        public int ProductID { get; set; }
        public int ProductSizeID { get; set; }
        public int Quantity { get; set; }
        public string Color { get; set; }
    
        public virtual Table_Products Table_Products { get; set; }
        public virtual Table_ProductSize Table_ProductSize { get; set; }
    }
}
