//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pooshineh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Table_ProductSize
    {
        public int ProductSizeID { get; set; }
        public int ProductColorID { get; set; }
        [Display(Name = "سایز")]
        [Required(ErrorMessage = "فیلد {0} اجباری است.")]
        public string ProductSize { get; set; }
        public int Quantity { get; set; }
    
        public virtual Table_ProductColor Table_ProductColor { get; set; }
    }
}
