//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pooshineh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class Table_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Orders()
        {
            this.Table_OrderDetails = new HashSet<Table_OrderDetails>();
        }
    
        public int OrderID { get; set; }
        [Display(Name = "آیدی سفارش")]
        public string OrderName { get; set; }
        public int CartID { get; set; }
        [Display(Name = "قیمت کل")]
        public int TotalCost { get; set; }
        [Display(Name = "تاریخ ثبت سفارش")]
        [DisplayFormat(DataFormatString = "{0: dddd, dd MMMM yyyy}")]
        public System.DateTime OrderDate { get; set; }
        [Display(Name = "وضعیت سفارش")]
        public string OrderStatus { get; set; }
        [Display(Name = "آدرس")]
        public string OrderAddress { get; set; }

        public virtual Table_Cart Table_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_OrderDetails> Table_OrderDetails { get; set; }
    }
}
