//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pooshineh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Table_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Products()
        {
            this.Table_CartItem = new HashSet<Table_CartItem>();
        }
    
        [Display(Name = "آیدی محصول")]
        public int ProductID { get; set; }
        [Display(Name = "آیدی دسته‌بندی")]
        public int CategoryID { get; set; }
        [Display(Name = "نام محصول")]
        [Required(ErrorMessage = "فیلد {0} اجباری است.")]
        public string ProductName { get; set; }
        [Display(Name = "توضیحات")]
        [Required(ErrorMessage = "فیلد {0} اجباری است.")]
        public string ProductDescription { get; set; }
        [Display(Name = "تصویر محصول")]
        [Required(ErrorMessage = "فیلد {0} اجباری است.")]
        public string ProductImagePath { get; set; }
        [Display(Name = "قیمت محصول")]
        [Required(ErrorMessage = "فیلد {0} اجباری است.")]
        public int ProductPrice { get; set; }
        [Display(Name = "موجودی")]
        [Required(ErrorMessage = "فیلد {0} اجباری است.")]
        public int ProductQuantity { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_CartItem> Table_CartItem { get; set; }
        public virtual Table_Categories Table_Categories { get; set; }
    }
}
